### ISSUE TITLE
testing jupysql-plugin on binder

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#13]
we are currently unable to test this on binder.

we can try using: https://mybinder.org/ and generate the URL by filling form. we'll need to add an [environment.yml](https://github.com/ploomber/jupysql/blob/8ce3334182733145dbea6ece9e3d59e30237788c/environment.yml#L21) so binder installs the package.

if that works, we can use that link and create a github action that automatically generates the appropriate link on each PR

**Comment by edublancas** [comment]
cc @yafimvo @idomic

**Comment by yafimvo** [comment]
Basically, it works.

This is the URL template that opens our quick-start guide in JupyterLab

```
https://mybinder.org/v2/gh/user/repo/branch_name?urlpath=lab/tree/doc/quick-start.md
```

We can install the plugin directly from git using this command

```
!pip install git+https://github.com/ploomber/jupysql-plugin.git#eqq=jupysql-plugin
```

then we must refresh the page and see the plugin.

---

However, I tried to test the table explorer feature using this approach and there are a few issues.

The build is a bit slow, unstable (error 500), cached, and looks like sometimes it limits the number of possible builds (see error)

```
Found built image, launching...
Too many users on this BinderHub! Try again soon.
```

Another issue is that in order to install the plugin we need nodejs version > 12. Currently, if we run jupysql repo on our Binder, for some reason it downgrades the version to 12.4.0.

This is the output from the build ([link to the build from my PR](https://jupysql--420.org.readthedocs.build/en/420/quick-start.html))
```
  Downgrade:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  - nodejs                         14.18.3  h8ca31f7_2            installed                      
  + nodejs                          12.4.0  he1b5a44_0            conda-forge/linux-64      18 MB

  Summary:

  Install: 125 packages
  Change: 4 packages
  Upgrade: 47 packages
  Downgrade: 1 packages

  Total download: 324 MB

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
```


According to binder docs, we can add nodejs to `environment.yml`. This works but the CI on Github is failing. I was able to upgrade the version to the latest version using [apt.txt file](https://mybinder.readthedocs.io/en/latest/using/config_files.html#apt-txt-install-packages-with-apt-get).

![image](https://github.com/ploomber/jupysql-plugin/assets/103026689/c8cd1363-6a35-4c30-bdad-b0cd2fc6ef0c)


Here is the link to a fresh clone of table_explorer PR which runs the latest version of nodejs, where you can install the plugin (remember to refresh the page)

https://mybinder.org/v2/gh/yafimvo/jupysql/table_explorer_binder_test?urlpath=lab/tree/doc/user-guide/table_explorer_demo.ipynb
